### ISSUE TITLE
THREE.js and dependencies

### ISSUE THREAD

**Issue by rodriguez-facundo** [openworm/geppetto-client#123]
If geppetto-client requires THREE v0.87.0 and another package requires THREE v0.109.0 then 2 versions of THREE will be installed. (for instance, react-force-graph requires THREE ^v0.109.0)

There is a global object THREE at runtime that will either be v0.87.0 or v0.109.0 but it can't be both. A solution would be to declare THREE as a `peerDependency` in geppetto-client.

##### yarn
```bash
├─ 3d-force-graph@1.56.3
 │ └─ three@0.109.0
└─ three@0.87.1
```

##### npm

```bash
└─┬ @geppettoengine/geppetto-client@1.0.0
  ├─┬ react-force-graph@1.27.1
  │ └─┬ 3d-force-graph@1.56.3
  │   └── three@0.109.0
  └── three@0.87.1
```

##### yarn

```bash
└─ three@0.109.0
```

##### npm 

```bash
└─┬ @geppettoengine/geppetto-client@1.0.0
  └─┬ react-force-graph@1.27.1
    └─┬ 3d-force-graph@1.56.3
      └── three@0.109.0
```

### Some more digging

---

Read as `Allows changes that do not modify the left-most non-zero digit`

(Don't modify 87)

```json
"dependencies": {
    "three": "^0.87.0"
  },
```

#### yarn

```bash
└─ three@0.87.1                                   < patch update
```

#### npm

```bash
my-app@0.1.0
└── three@0.87.1                               < patch update
```

In the other hand, for react:

(Don't modify 15)

```json
"dependencies": {
    "react": "^15.5.0"
  },
```

#### yarn

```bash
└─ react@15.6.2                                    < minor version update
```

#### npm

```bash
my-app@0.1.0
└── react@15.6.2                               < minor version update
```

---

Read as `bigger than`

```json
"dependencies": {
    "three": ">0.87.0"
  },
```

#### yarn

```bash
└─ three@0.110.0
```

#### npm

```bash
my-app@0.1.0
└── three@0.110.0
```

--- 

Thoughts @filippomc @tarelli?  I am not sure how THREE 109 would impact geppetto

**Comment by filippomc** [comment]
@rodriguez-facundo I'd try with the update the 0.87 dependency and see if the 3d view is breaking the tests and also a manual inspection. 
I'm not optimistic about the peer dependency if a global object is involved in runtime.

**Comment by rodriguez-facundo** [comment]
All good now. three-forcegraph was updated to solve dependency issue.
