### ISSUE TITLE
Update the webpack configuration to have uglify compatible with ES6

### ISSUE THREAD

**Issue by tarelli** [openworm/geppetto-client#13]
See here https://github.com/mishoo/UglifyJS2/issues/659 we'll likely need terser-webpack-plugin

**Comment by rodriguez-facundo** [comment]
Wasn't it related to this: https://github.com/openworm/geppetto-application/blob/5e66e48df570a95914d1a343513d9301628b68e8/tsconfig.json#L7 changing to e6 did the trick?

**Comment by tarelli** [comment]
mm to my knowledge `npm run build` still doesn't work unless you tell me otherwise

**Comment by rodriguez-facundo** [comment]
You are right... there is still an issue there
https://github.com/webpack/webpack/issues/2972

**Comment by tarelli** [comment]
Fixed now, merged to development.
