### ISSUE TITLE
Trigger geppetto-application testing when a geppetto bundle get updated

### ISSUE THREAD

**Issue by ddelpiano** [openworm/geppetto-client#20]
Retrigger the geppetto-application Travis' tests when any geppetto bundle gets updated.

**Comment by tarelli** [comment]
Proposal from Robb: on every Travis configuration we add an on_success section which will have a command to retrigger the geppetto-application travis build. This will require creating a web_hook with the proper security settings. 

Robb is prototyping this within some VFB repos and then once that works we can port it to Geppetto.

**Comment by Robbie1977** [comment]
Code is here: https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/vfb_geppetto_application/travis/trigger-build.js 

Run with this code: https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/blob/vfb_geppetto_application/.travis.yml#L32
```
before_script:
- npm install travis-ci

after_success:
- node trigger-build.js
```
Instruction here: https://iranzo.github.io/blog/2018/12/11/travis-to-trigger-build-in-another-repo/ 

Instructions for getting key Note that this is stored in 'TRATOKEN':
```
The access token
The whole reason this works is because we are authenticating to GitHub using a Personal Access Token (stored in GH_TOKEN). This is an OAuth token that you can create when using Two-Factor Auth to authenticate 3rd party tools like Visual Studio, or in our case, authenticating in a script.

You can generate a token by:

Going to Applications in your Settings
Clicking "Generate New Token"
Selecting your permissions (for Travis, all you need is public_repo)
Once created, copy the token to your clipboard (you must regenerate it if you lose it)
Now we need to configure Travis to expose this token securely to our script.

On Travis, go to the Settings of your project (top-right)
Click the "Environment Variables" tab (and ensure Build Pull Requests is 'Off')
Create a new environment variable called GH_TOKEN
In the Value field, paste in your token, being sure to remove any trailing whitespace
Ensure "Display value in build logs" is Off
Once created, you're all set! GH_TOKEN will now be available to your deploy.sh script.
```
