### ISSUE TITLE
Fix canvas reset when new instances are added to the scene

### ISSUE THREAD

**Issue by ddelpiano** [openworm/geppetto-client#204]
Currently when we add a new instance to the model/scene, when this is loaded in the canvas 3d the component reset (as per gif attached).

![canvas_reset](https://user-images.githubusercontent.com/37704177/77692000-c42c2f00-6f9d-11ea-9aa4-000169055691.gif)

We need to fix this behaviour and remove the reset, the canvas has to stay in the same position and zoom no matter what we add to the scene and to the 3d canvas. (e.g. point clouds, meshes, etc).

**Comment by jrmartin** [comment]
@ddelpiano Would an acceptable solution be that instead of resetting the camera view when an instance is added, we zoom in to view the instance that was added?
