### ISSUE TITLE
Fix dependency management

### ISSUE THREAD

**Issue by filippomc** [openworm/geppetto-client#42]
Code compilation and packing dependencies should be specified as dev dependencies. 
Starting point:

```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "10.0.1",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-object-assign": "^6.8.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "3.6.0",
    "webpack-dev-server": "2.8.2",
    "html-webpack-plugin": "2.30.1",
    "copy-webpack-plugin": "^4.6.0",
    "eslint": "5.13.0",
    "extract-text-webpack-plugin": "3.0.0"
  }
```

**Comment by filippomc** [comment]
Or maybe all of this goes on the application, which is doing the packaging? In this case, geppetto-client should be a proper dependency. It shouldn't work without being a dependency in fact, but it does. There's something weird in the way the application is referring the client.

**Comment by afonsobspinto** [comment]
`babel-polyfill` appears to be necessary at runtime: 
https://stackoverflow.com/questions/40143357/do-you-put-babel-and-webpack-in-devdependencies-or-dependencies#comment73370114_40143446

**Comment by tarelli** [comment]
The goal should be 
- [ ] Identify all dependencies that should be devDependencies and move them there. Test.
- [ ] Check the size of the main.bundle.js and common.bundle.js before and after to establish whether there was an impact.
