### ISSUE TITLE
Plot widget not working

### ISSUE THREAD

**Issue by jrmartin** [openworm/geppetto-client#50]
The Plot widget doesn't work using development branch of geppetto-client. The Plot widgets don't get created at startup when loading the Hodgkin project, attempting to open a new Plot from within Geppetto doesn't work either (let that be through spotlight, control panel or command), the latter issue happens in all projects.

Chrome console error:
![Screenshot from 2019-07-17 14-47-41](https://user-images.githubusercontent.com/4562825/61414213-45291780-a8a2-11e9-89c8-8e78f8a23a57.png)

**Comment by ddelpiano** [comment]
note for whoever look at it, this reminds me of the problem we had due to the same library used as dependency but with different versions of it, solved flatting the node_modules with

```
modules: [
        path.resolve(__dirname, 'geppetto-client', 'node_modules'),
        path.resolve(__dirname, geppetto_client_path, 'node_modules'),
        'node_modules'
      ],
```

**Comment by rodriguez-facundo** [comment]
I spotted this yesterday: https://github.com/openworm/geppetto-client/issues/49 @jrmartin @ddelpiano 

That `modules` key in `webpack.config.js` can cause issues when you are trying to use a different version of a package in development mode.

**Comment by rodriguez-facundo** [comment]
And another thing to bear in mind is that if we use absolute paths in `modules`, then webpack will only look for packages in the specified folder. If we use relative paths, then webpack will move up in the file system scanning all the `node_module` folders it can find

**Comment by jrmartin** [comment]
Thanks guys, fixed it. I already had the changes in my webpack.config.js to flatten modules, so it was something else. I deleted the node_modules folder in my computer, did a 'npm install' again and now it works. It'll probably keep on happening when package versions are updated, but closing this issue since #49 will take care of it
